import java.time.Instant
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

buildscript {
    repositories {
        mavenCentral()
        maven { url = "https://repo.grails.org/grails/restricted" }
        maven {
            url = 'https://repository.apache.org/content/groups/snapshots'
            content {
                includeVersionByRegex('org[.]apache[.](grails|groovy).*', '.*', '.*-SNAPSHOT')
            }
        }
        gradlePluginPortal()
    }
    dependencies {
        classpath platform("org.apache.grails:grails-bom:$grailsVersion")
        classpath "org.apache.grails:grails-gradle-plugins"
    }
}

version = projectVersion
group "io.github.gpc"

apply plugin: 'java-library'
apply plugin: "org.apache.grails.gradle.grails-plugin"
apply plugin: 'org.apache.grails.gradle.grails-publish'

ext {
    buildInstant = java.util.Optional.ofNullable(System.getenv("SOURCE_DATE_EPOCH"))
            .filter(s -> !s.isEmpty())
            .map(Long::parseLong)
            .map(Instant::ofEpochSecond)
            .orElseGet(Instant::now)
    formattedBuildDate = DateTimeFormatter.ISO_INSTANT.format(buildInstant)
    buildDate = (buildInstant as Instant).atZone(ZoneOffset.UTC) // for reproducible builds
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.grails.org/grails/restricted' }
    maven {
        url = 'https://repository.apache.org/content/groups/snapshots'
        content {
            includeVersionByRegex('org[.]apache[.](grails|groovy).*', '.*', '.*-SNAPSHOT')
        }
    }
}

dependencies {
    compileOnly platform("org.apache.grails:grails-bom:$grailsVersion")
    compileOnly 'org.apache.grails:grails-dependencies-starter-web'
    implementation "org.apache.grails:grails-cache"

    // https://mvnrepository.com/artifact/com.google.guava/guava
    implementation "com.google.guava:guava:${guavaVersion}"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
}

grailsPublish {
    githubSlug = 'gpc/grails-cache-guava'
    license {
        name = 'Apache-2.0'
    }
    title = 'Grails Cache Guava Plugin'
    desc = 'The Guava cache provides a simple in memory cache with maximal capacity and TTL.'
    developers = [
            sbglasius   : 'Søren Berg Glasius'
    ]
}
